baseURL = "/"
languageCode = "en-gb"
defaultContentLanguage = "en"
googleAnalytics = ""

title = "Messaging Principles"
theme = "techdoc"

metaDataFormat = "yaml"
enableGitInfo = true
enableEmoji = true

pygmentsStyle = "manni"
pygmentsCodeFences = true
pygmentsUseClasses = false

[Params]
    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = "#000078"

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

# Blackfriday Markdown
[blackfriday]
hrefTargetBlank = true

# Deployment
[deployment]
[[deployment.targets]]
name = "s3website"
URL = "s3://messagingprinciples?region=eu-west-2"